# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 31f973d9986208e635d7382f42e3d058c759eadc17620de57c46ebc5a5c0f301f950034c85e59faf49dc96357de26b41a010a33ea0673affb520fb84d68940a5

test:
  secret_key_base: 371fe9d338d6a3831db9a3d2f9df798a122e97aa8683279fdf79606afabde2a63363ede61fc5b2428e921388aa189b424b546287aaa2c75d007114dfc233f616

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
